name: Build

env:
  CIBW_BEFORE_ALL_LINUX: yum install -y http://springdale.princeton.edu/data/springdale/6/x86_64/os/Computational/swig307-3.0.7-3.sdl6.x86_64.rpm && alias swig='swig307'
  CIBW_BEFORE_ALL_WINDOWS: choco install swig -f -y
  CIBW_BEFORE_ALL_MACOS: brew install swig


on: [push, pull_request]

jobs:
  
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Install Visual C++
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
